//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELE_CALLER_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TELE_CALLER_MASTER()
        {
            this.USER_PERMISSIONS = new HashSet<USER_PERMISSIONS>();
        }
    
        public string TCM_ID { get; set; }
        public string TCM_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PERMISSIONS> USER_PERMISSIONS { get; set; }
    }
}
