//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PERMISSIONS
    {
        //internal bool IsSelected;

        public int ID { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> ViewPermission { get; set; }
        public Nullable<bool> AddPermission { get; set; }
        public Nullable<bool> EditPermission { get; set; }
        public Nullable<bool> DeletePermission { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual TELE_CALLER_MASTER TELE_CALLER_MASTER { get; set; }

       
    }
}
